# Generated by Django 5.2.4 on 2026-07-10 06:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number (7–15 digits, optional leading +).', regex='^\\+?\\d{7,15}$')]),
        ),
    ]
