# Generated by Django 5.2.4 on 2026-07-10 06:36

import apps.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/images/blog/', validators=[apps.core.validators.MaxFileSizeValidator(3), apps.core.validators.FileExtensionAllowlistValidator(['.jpg', '.jpeg', '.png', '.webp'])]),
        ),
    ]
