# Generated by Django 5.2.4 on 2026-07-10 06:36

import apps.core.validators
import apps.uploads.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedfile',
            name='file',
            field=models.FileField(upload_to=apps.uploads.models.generic_upload_path, validators=[apps.core.validators.MaxFileSizeValidator(10), apps.core.validators.FileExtensionAllowlistValidator(['.pdf', '.doc', '.docx', '.zip', '.jpg', '.jpeg', '.png'])]),
        ),
    ]
