# Generated by Django 5.2.4 on 2026-07-10 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_type', models.CharField(choices=[('contact_submitted', 'Contact Submitted'), ('quotation_submitted', 'Quotation Submitted'), ('application_submitted', 'Application Submitted'), ('newsletter_subscribed', 'Newsletter Subscribed'), ('blog_viewed', 'Blog Viewed')], max_length=50)),
                ('source_page', models.CharField(blank=True, max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
