# Generated by Django 5.2.4 on 2026-07-10 06:36

import apps.careers.models
import apps.core.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='certificate',
            field=models.FileField(blank=True, null=True, upload_to=apps.careers.models.certificate_upload_path, validators=[apps.core.validators.MaxFileSizeValidator(5), apps.core.validators.FileExtensionAllowlistValidator(['.pdf', '.jpg', '.jpeg', '.png'])]),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number (7–15 digits, optional leading +).', regex='^\\+?\\d{7,15}$')]),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='resume',
            field=models.FileField(upload_to=apps.careers.models.resume_upload_path, validators=[apps.core.validators.MaxFileSizeValidator(5), apps.core.validators.FileExtensionAllowlistValidator(['.pdf', '.doc', '.docx'])]),
        ),
    ]
